version: '2.1'

services:
  head-first-design-patterns-1:
    image: head-first-design-patterns-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - :
      - 5005:5005
    